### ISSUE TITLE
Arrumar telhas na marcenaria

### ISSUE THREAD

**Issue by rennerocha** [lhc/meta#10]
As telhas nos fundos parecem estar ou quebradas ou fora de lugar. Está entrando água quando chove.
Precisa subir no telhado e arrumar as telhas e trocar as que estiverem quebradas. Temos algumas telhas sobrando perto do portão da garagem.

**Comment by rennerocha** [comment]
Precisamos de uma escada para subir no telhado.

**Comment by ffrediani** [comment]
O Danilo tem uma maneira fácil de subir no telhado, além dele ser mais leve para andar ali. Acredito que ele pode nos ajudar com esta inspeção.

**Comment by rennerocha** [comment]
Eu só não subi ainda por falta de escada mesmo, eu não tenho uma. Se o Danilo tem um jeito fácil de subir lá sem se arrebentar e sem arrebentar o telhado, seria ideal que ele fizesse isso o mais rápido possível, antes que estrague ainda mais o forro lá de dentro (a bancada já estragou mas vou fazer outra).
