### ISSUE TITLE
Campainha IoT

### ISSUE THREAD

**Issue by EstevesDouglas** [lhc/meta#12]
Verificar circuito e pilhas  da campainha. Item parou de funcionar.

Deixar uma tomada exclusiva para o computador com a caixa de som no laboratório para tocar som da campainha.

**Comment by ffrediani** [comment]
Valeu pelo aviso Douglas. Com relação as pilhas é questão de substituição e parece que alguem esbarrou com ela e o led de status soltou 1 dos fios então precisa soldar novamente.
A caixa de som do "servidor" da campainha é ligada no próprio USB do computador que precisa estar ligado a uma tomada exclusive (acredito que já esta). Na outra esta ligada uma régua.

**Comment by EstevesDouglas** [comment]
Fernando arrumou Camapinha IoT e servidor com caixa de som ficou no laboratório de eletrônica.
