### ISSUE TITLE
Arrumar Campainha IoT

### ISSUE THREAD

**Issue by EstevesDouglas** [lhc/meta#22]
Refeita a solda da Campainha, comprar e adicionar novas pilhas,
Caixa com a Campainha IoT ficou no laboratório de eletrônica. 

- [x] Pilhas [comprar Duas AA de boa qualidade]
- [x]  Servidor funcionando novamente.
- [x] Caixa para o servidor.

**Comment by djunho** [comment]
Podemos tentar chamar uma galera para integrar com o painel de Led.

Nesse caso seria uma aplicação no servidor que ao tocar um som, tb manda uma imagem para o Painel.
https://github.com/lhc/nodeLHC_WS2811_LED_Controller/issues/4

**Comment by EstevesDouglas** [comment]
Excelente @djunho.

**Comment by EstevesDouglas** [comment]
Comprei pilhas novas e refiz a instalação.

**Comment by EstevesDouglas** [comment]
Alterei o servidor da Campainha, adicionei uma caixa de som padrão.

**Comment by EstevesDouglas** [comment]
Esperando nova caixa de som do Rubens.

**Comment by EstevesDouglas** [comment]
https://thingspeak.com/channels/58985/charts/1?&median=10&results=5&dynamic=true&type=spline  Data para acompanhar dispositivo.
