### ISSUE TITLE
 Colocar uma porta na marcenaria

### ISSUE THREAD

**Issue by ffrediani** [lhc/meta#4]
A marcenaria está sem porta e precisa de uma para proteger-la quando o LHC está fechado ou da chuva. Sera necessário também a troca do batente.

**Comment by rennerocha** [comment]
Planilha com lista dos materiais necessários e quem está participando da vaquinha:
https://docs.google.com/spreadsheets/d/1mZmdcVLLamlP0Fa7ljrLHkvitQuHj1YJKSG8lmui3Zk/edit?usp=sharing

**Comment by rennerocha** [comment]
A porta já está no lugar, mas está travando. Precisa ajustar as dobradiças para se encaixarem no batente corretamente, assim a porta vai fechar sem travar....
