### ISSUE TITLE
Arrumar a placa analógica do monitor do arcade

### ISSUE THREAD

**Issue by ffrediani** [lhc/meta#6]
O arcade do LHC funciona porém possui um problema na placa analogica da TV de tubo aonde metade da tela fica preta quando é ligada. É necessário conhecimento com manutenção de TVs antigas e principalmente saber mexer com flyback para evitar o risco de choque eletrico. Em uma análise prévia foi sugerido que a troca de capacitores pode resolver o problema.

**Comment by EstevesDouglas** [comment]
Lançar na lista para conseguir o contato de algum técnico para arrumar a placa conversor VGA.
