### ISSUE TITLE
Arrumar a estrutura e cobertura da Lavanderia/Churrasqueira

### ISSUE THREAD

**Issue by ffrediani** [lhc/meta#7]
A estrutura coberta da lavanderia não está nas melhores condições. É interessante reformar a parte de estrutura e da cobertura para garantir por exemplo a continuidade dos churrascos em dias que a chuva chega de surpresa.

**Comment by rennerocha** [comment]
Basicamente precisamos de:
- vigas de madeira
- telhas
- cimento
- alguns parafusos

**Comment by lpereira** [comment]
Outra alternativa é metalon + telha metálica, e aí chumbar na parede. Dá inclusive pra fazer um abrigo para a porta, que se fica aberta quando chove, molha a cozinha. Provavelmente sai mais barato (e mais rápido) se fizer de metal. Tem máquina de solda no LHC mas dá pra aparafusar também.

Cimento+areia também ajuda pra refazer o reboco perto do tanque, que tá caindo... teria que chapiscar e rebocar. É de boa fazer, só precisa tirar as vigas que estão lá.

**Comment by EstevesDouglas** [comment]
Zeh está cuidando desta atividade.

em processo de construção.
