### ISSUE TITLE
Repintura da fachada

### ISSUE THREAD

**Issue by ffrediani** [lhc/meta#8]
A aparência externa do LHC está bem precária atualmente, seria interessante uma repintura da fachada. Poderíamos usar tinta látex ou cal + aditivo fixador (mais barato, porém menos durável).

**Comment by rennerocha** [comment]
Acho que com a arrumação do jardim, a fachada já está com uma aparência razoável.... Não acho que seja necessário uma pintura nesse momento. Também não precisamos que o LHC chame muita atenção na rua....
O que acham?

**Comment by jsbueno** [comment]
Achoq ue pitnar é (1) uma atividade legl de integração; (2) nada que vá chamar a atençaõ demais e (3) algo que vai fazer todo mundo se sentir melhor ao chegar.  :-)

**Comment by rennerocha** [comment]
(1) Conheço atividades bem mais legais de integração :-)
(2) Sim, se for pintar, podia achar esse cinza que já está pintado para ficar mais fácil. Mas nada que indique que lá é o LHC.
(3) Acho que o que está mais feio, são as pichações na muretinha. Só de tirar elas já melhoraria bastante...

**Comment by ffrediani** [comment]
Uma melhora da fachada é sempre bem vinda e não necessariamente significa que ira chamar atenção se mantermos a mesma aparência e cores, além de tornar o local mais convidativo para aqueles que frequentam. Também para mostrar aos possíveis "hospedes noturnos" que a casa esta ocupada e que tem gente ali.

Esse ideia originalmente veio do Alexandre Fernandes (eu só coloquei aqui no Github), acredito que ele tenha mais detalhes e possa compartilhar conosco.

A principio só uma mão de tinta do jeito que ele falou (tinta látex ou cal) já ajuda a dar uma aparência melhor de limpeza.

**Comment by jsbueno** [comment]
Da minha mudança aqui fiquei cm mais ou menos 1/3 de lata (6-8 l) de tinta "boa mesmo"(tm)  - só que está colorizada em bege->pessego.  

Arrumo para o LHC de boa - mas acho que é muito diferente da cor da fachada.

**Comment by rennerocha** [comment]
Acho que o que está pior na fachada é a muretinha com aquelas pichações. A casa em si, na minha opinião não está feia. Será que fica muito estranho pintar só a muretinha de bege ???
