### ISSUE TITLE
 Lavar e desencardir o piso dos cômodos

### ISSUE THREAD

**Issue by ffrediani** [lhc/meta#9]
Hoje o piso da sede está muito sujo e encardido, muita poeira por debaixo dos móveis. Uma limpeza mais pesada, com produtos adequados, traria um ambiente mais agradável para os frequentadores e bem visto pelos visitantes.

**Comment by rennerocha** [comment]
Precisamos comprar o limpa piso para tentar desencardir o banheiro.
Acho que esse é o piso que dá mais sensação de sujeira na casa.

**Comment by lpereira** [comment]
Tem um pouco de soda cáustica que já foi usada para limpar o piso da cozinha (que é mosaico hidráulico).
